# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pshri\Documents\PythonFiles\ComputerProject\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True) #enable highdpi scaling
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(362, 361)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 120, 241, 41))
        self.label.setStyleSheet("QLabel{\n"
"    font:bold 22px;\n"
"\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 180, 191, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font:bold 12px;\n"
"    background-color:#1c1c2c;\n"
"    border-radius:20px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius:5px;\n"
"    background:white;\n"
"    border:2px solid #1c1c2c;\n"
"    color:#1c1c2c;\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Computer Project"))
        self.pushButton.setText(_translate("Form", "View database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
